name: CI
on:
    push:
    pull_request:
    workflow_run:
        workflows: ["Generate Web API Index"]
        types:
            - completed
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: ["16", "18", "20"]
        name: Node ${{ matrix.node }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Set up Node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}
            - name: Install
              run: npm install
            - name: Build
              run: npm run build
            - name: Test
              run: npm run test
            - name: Lint
              run: npm run lint
            - name: Circular dependency check
              uses: gerrit0/circular-dependency-check@v2
              with:
                  entry: dist/index.js
