name: CI
on:
    push:
    pull_request:
    workflow_run:
        workflows: ["Generate Web API Index"]
        types:
            - completed
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: ["18", "20", "22"]
        name: Node ${{ matrix.node }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}
            - name: Install pnpm
              run: npm install -g pnpm@10
            - name: Install
              run: pnpm install
            - name: Build
              run: pnpm build
            - name: Test
              run: pnpm  test
            - name: Lint
              run: pnpm lint
            - name: Circular dependency check
              uses: gerrit0/circular-dependency-check@v2
              with:
                  entry: dist/index.js
