name: CI
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: ["14", "16"]
        name: Node ${{ matrix.node }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Set up Node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}
            - name: Install
              run: npm install
            - name: Build
              run: npm run build
            - name: Lint
              run: npm run lint
            - name: Circular dependency check
              uses: gerrit0/circular-dependency-check@v1
              with:
                  entry: dist/index.js
